"""Add NER Entity models

Revision ID: 0aef2a09f209
Revises: 8cf44e862a10
Create Date: 2026-02-13 08:24:56.986547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0aef2a09f209'
down_revision: Union[str, None] = '8cf44e862a10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ner_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ner_entities_id'), 'ner_entities', ['id'], unique=False)
    op.create_index(op.f('ix_ner_entities_name'), 'ner_entities', ['name'], unique=False)
    op.create_index(op.f('ix_ner_entities_type'), 'ner_entities', ['type'], unique=False)
    op.create_table('node_ner_entities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('doc_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['ner_entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_node_ner_entities_doc_id'), 'node_ner_entities', ['doc_id'], unique=False)
    op.create_index(op.f('ix_node_ner_entities_id'), 'node_ner_entities', ['id'], unique=False)
    op.create_index(op.f('ix_node_ner_entities_node_id'), 'node_ner_entities', ['node_id'], unique=False)
    op.drop_index(op.f('ix_trishard_relationships_id'), table_name='trishard_relationships')
    op.drop_index(op.f('ix_trishard_relationships_relation_type'), table_name='trishard_relationships')
    op.drop_table('trishard_relationships')
    op.drop_index(op.f('ix_relationships_relation_type'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index(op.f('ix_trishard_entities_id'), table_name='trishard_entities')
    op.drop_index(op.f('ix_trishard_entities_name'), table_name='trishard_entities')
    op.drop_index(op.f('ix_trishard_entities_type'), table_name='trishard_entities')
    op.drop_table('trishard_entities')
    op.drop_index(op.f('ix_entities_name'), table_name='entities')
    op.drop_index(op.f('ix_entities_type'), table_name='entities')
    op.drop_table('entities')
    op.drop_index(op.f('ix_audit_ledger_timestamp'), table_name='audit_ledger')
    op.drop_table('audit_ledger')
    op.drop_index(op.f('ix_trishard_chunks_id'), table_name='trishard_chunks')
    op.drop_table('trishard_chunks')

    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')

    op.create_table('trishard_chunks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], name=op.f('trishard_chunks_doc_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trishard_chunks_pkey'))
    )
    op.create_index(op.f('ix_trishard_chunks_id'), 'trishard_chunks', ['id'], unique=False)
    op.create_table('trishard_relationships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('source_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('evidence_source_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['evidence_source_id'], ['document.id'], name=op.f('trishard_relationships_evidence_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['trishard_entities.id'], name=op.f('trishard_relationships_source_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_id'], ['trishard_entities.id'], name=op.f('trishard_relationships_target_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('trishard_relationships_pkey'))
    )
    op.create_index(op.f('ix_trishard_relationships_relation_type'), 'trishard_relationships', ['relation_type'], unique=False)
    op.create_index(op.f('ix_trishard_relationships_id'), 'trishard_relationships', ['id'], unique=False)
    op.create_table('audit_ledger',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('query', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('retrieval_path', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('synthesis_trace', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('audit_ledger_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_ledger_pkey'))
    )
    op.create_index(op.f('ix_audit_ledger_timestamp'), 'audit_ledger', ['timestamp'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('doc_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['doc_id'], ['document.id'], name='entities_doc_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='entities_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_entities_type'), 'entities', ['type'], unique=False)
    op.create_index(op.f('ix_entities_name'), 'entities', ['name'], unique=False)
    op.create_table('trishard_entities',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('metadata_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trishard_entities_pkey'))
    )
    op.create_index(op.f('ix_trishard_entities_type'), 'trishard_entities', ['type'], unique=False)
    op.create_index(op.f('ix_trishard_entities_name'), 'trishard_entities', ['name'], unique=False)
    op.create_index(op.f('ix_trishard_entities_id'), 'trishard_entities', ['id'], unique=False)
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('source_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('target_entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('evidence', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('relationships_source_entity_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('relationships_target_entity_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('relationships_pkey'))
    )
    op.create_index(op.f('ix_relationships_relation_type'), 'relationships', ['relation_type'], unique=False)
    op.drop_index(op.f('ix_node_ner_entities_node_id'), table_name='node_ner_entities')
    op.drop_index(op.f('ix_node_ner_entities_id'), table_name='node_ner_entities')
    op.drop_index(op.f('ix_node_ner_entities_doc_id'), table_name='node_ner_entities')
    op.drop_table('node_ner_entities')
    op.drop_index(op.f('ix_ner_entities_type'), table_name='ner_entities')
    op.drop_index(op.f('ix_ner_entities_name'), table_name='ner_entities')
    op.drop_index(op.f('ix_ner_entities_id'), table_name='ner_entities')
    op.drop_table('ner_entities')
    # ### end Alembic commands ###
