"""Chat history and chat items

Revision ID: 1031bd06f759
Revises: c995f8258ca0
Create Date: 2025-02-28 11:17:07.835534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1031bd06f759'
down_revision: Union[str, None] = 'c995f8258ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('title_generated', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id')
    )
    op.create_index('idx_chat_history_active', 'chat_history', ['is_deleted', 'is_archived'], unique=False)
    op.create_index('idx_chat_history_user_created', 'chat_history', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_created_at'), 'chat_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_chat_history_is_archived'), 'chat_history', ['is_archived'], unique=False)
    op.create_index(op.f('ix_chat_history_is_deleted'), 'chat_history', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_chat_history_title'), 'chat_history', ['title'], unique=False)
    op.create_index(op.f('ix_chat_history_user_id'), 'chat_history', ['user_id'], unique=False)
    op.create_table('chat_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('sender', sa.String(length=225), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Enum('THUMBS_UP', 'THUMBS_DOWN', 'HELPFUL', 'NOT_HELPFUL', 'IRRELEVANT', name='rating'), nullable=True),
    sa.Column('status', sa.Enum('DELIVERED', 'READ', 'DELETED', 'EDITED', name='messagestatus'), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_history.conversation_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['chat_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_items_conv_index', 'chat_items', ['conversation_id', 'index'], unique=False)
    op.create_index('idx_chat_items_sender', 'chat_items', ['conversation_id', 'sender'], unique=False)
    op.create_index(op.f('ix_chat_items_conversation_id'), 'chat_items', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_items_sender'), 'chat_items', ['sender'], unique=False)
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')al
    op.drop_index(op.f('ix_chat_items_sender'), table_name='chat_items')
    op.drop_index(op.f('ix_chat_items_conversation_id'), table_name='chat_items')
    op.drop_index('idx_chat_items_sender', table_name='chat_items')
    op.drop_index('idx_chat_items_conv_index', table_name='chat_items')
    op.drop_table('chat_items')
    op.drop_index(op.f('ix_chat_history_user_id'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_title'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_is_deleted'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_is_archived'), table_name='chat_history')
    op.drop_index(op.f('ix_chat_history_created_at'), table_name='chat_history')
    op.drop_index('idx_chat_history_user_created', table_name='chat_history')
    op.drop_index('idx_chat_history_active', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
