"""Document and version

Revision ID: 24017c31b626
Revises: 9c2aa080df79
Create Date: 2025-02-14 12:07:22.603912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24017c31b626'
down_revision: Union[str, None] = '9c2aa080df79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'document_versions', ['current_version_id'], ['id'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'current_version_id')
    # ### end Alembic commands ###
