"""Version cascade

Revision ID: 34878fd04072
Revises: b50fbd4fe583
Create Date: 2025-02-15 08:49:41.022789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34878fd04072'
down_revision: Union[str, None] = 'b50fbd4fe583'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_document_document_version', 'document_versions', type_='unique')
    op.create_unique_constraint('uix_document_version', 'document_versions', ['document_id', 'version_number'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint('uix_document_version', 'document_versions', type_='unique')
    op.create_unique_constraint('uix_document_document_version', 'document_versions', ['document_id', 'version_number'])
    # ### end Alembic commands ###
