"""Metadata_field

Revision ID: 35245d1ec957
Revises: fe4501b3fbe3
Create Date: 2025-05-11 08:43:20.147449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35245d1ec957'
down_revision: Union[str, None] = 'fe4501b3fbe3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('doc_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('document', 'tags')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('document', sa.Column('tags', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('document', 'doc_metadata')
    # ### end Alembic commands ###
