"""google_drive_docs

Revision ID: 4ab215adb170
Revises: aa67a3d40eb8
Create Date: 2025-12-25 20:12:20.963931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ab215adb170'
down_revision: Union[str, None] = 'aa67a3d40eb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('ingest_status', sa.String(length=50), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auth_id'], ['google_drive_auth.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_drive_file_id'), 'google_drive_file', ['id'], unique=False)
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_google_drive_file_id'), table_name='google_drive_file')
    op.drop_table('google_drive_file')
    # ### end Alembic commands ###
