"""update set cascade

Revision ID: 7a85219676f4
Revises: 28c2430b6420
Create Date: 2024-03-20 10:47:35.321054

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a85219676f4'
down_revision: Union[str, None] = '28c2430b6420'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('document_department_association_department_id_fkey', 'document_department_association', type_='foreignkey')
    op.drop_constraint('document_department_association_document_id_fkey', 'document_department_association', type_='foreignkey')
    op.create_foreign_key(None, 'document_department_association', 'document', ['document_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.create_foreign_key(None, 'document_department_association', 'departments', ['department_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'document_department_association', type_='foreignkey')
    op.drop_constraint(None, 'document_department_association', type_='foreignkey')
    op.create_foreign_key('document_department_association_document_id_fkey', 'document_department_association', 'document', ['document_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    op.create_foreign_key('document_department_association_department_id_fkey', 'document_department_association', 'departments', ['department_id'], ['id'], onupdate='SET NULL', ondelete='SET NULL')
    # ### end Alembic commands ###
