"""update chat model

Revision ID: 891c3c70c81f
Revises: 4aae9ee1ebd1
Create Date: 2025-10-02 15:16:15.166325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '891c3c70c81f'
down_revision: Union[str, None] = '4aae9ee1ebd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_item_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chat_item_id', sa.UUID(), nullable=False),
    sa.Column('old_content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('edited_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['chat_item_id'], ['chat_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_item_versions_item_id', 'chat_item_versions', ['chat_item_id'], unique=False)
    op.add_column('chat_history', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_index('gin_chat_items_content', 'chat_items', ['content'], unique=False, postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_index('gin_chat_items_content', table_name='chat_items', postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    op.drop_column('chat_history', 'deleted_at')
    op.drop_index('idx_chat_item_versions_item_id', table_name='chat_item_versions')
    op.drop_table('chat_item_versions')
    # ### end Alembic commands ###
