"""decouple_document_version

Revision ID: 8cf44e862a10
Revises: cbb350a4679c
Create Date: 2026-01-24 04:06:56.112371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cf44e862a10'
down_revision: Union[str, None] = 'cbb350a4679c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_current_version_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'current_version_id')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('document', sa.Column('current_version_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_current_version_id_fkey'), 'document', 'document_versions', ['current_version_id'], ['id'])
    # ### end Alembic commands ###
