"""new

Revision ID: 93338be47304
Revises: 4aae9ee1ebd1
Create Date: 2025-12-25 14:11:13.762348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93338be47304'
down_revision: Union[str, None] = '4aae9ee1ebd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('idx_chat_item_versions_item_id'), table_name='chat_item_versions')
    # op.drop_table('chat_item_versions')
    # op.drop_column('chat_history', 'deleted_at')
    # op.drop_index(op.f('gin_chat_items_content'), table_name='chat_items', postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    # op.create_index(op.f('gin_chat_items_content'), 'chat_items', ['content'], unique=False, postgresql_ops={'content': 'jsonb_path_ops'}, postgresql_using='gin')
    # op.add_column('chat_history', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    # op.create_table('chat_item_versions',
    # sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('chat_item_id', sa.UUID(), autoincrement=False, nullable=False),
    # sa.Column('old_content', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    # sa.Column('edited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    # sa.ForeignKeyConstraint(['chat_item_id'], ['chat_items.id'], name=op.f('chat_item_versions_chat_item_id_fkey'), ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id', name=op.f('chat_item_versions_pkey'))
    # )
    # op.create_index(op.f('idx_chat_item_versions_item_id'), 'chat_item_versions', ['chat_item_id'], unique=False)
    # ### end Alembic commands ###
    pass
