"""Removed index from chat_items

Revision ID: a26f510dee70
Revises: a6f9bef62055
Create Date: 2025-03-02 11:50:52.050327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a26f510dee70'
down_revision: Union[str, None] = 'a6f9bef62055'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_chat_items_conv_index', table_name='chat_items')
    op.create_index('idx_chat_items_created', 'chat_items', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_chat_items_created_at'), 'chat_items', ['created_at'], unique=False)
    op.drop_column('chat_items', 'index')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.add_column('chat_items', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_chat_items_created_at'), table_name='chat_items')
    op.drop_index('idx_chat_items_created', table_name='chat_items')
    op.create_index('idx_chat_items_conv_index', 'chat_items', ['conversation_id', 'index'], unique=False)
    # ### end Alembic commands ###
