"""document version

Revision ID: a5d108cc12e3
Revises: 4e9976d93ac9
Create Date: 2025-05-24 15:20:29.490870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5d108cc12e3'
down_revision: Union[str, None] = '4e9976d93ac9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'document_versions', ['current_version_id'], ['id'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'current_version_id')
    # ### end Alembic commands ###
