"""A

Revision ID: a6f9bef62055
Revises: 08e34756fe5b
Create Date: 2025-03-02 11:13:36.486845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6f9bef62055'
down_revision: Union[str, None] = '08e34756fe5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_chat_items_conversation_index', 'chat_items', type_='unique')
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.create_unique_constraint('uq_chat_items_conversation_index', 'chat_items', ['conversation_id', 'index'])
    # ### end Alembic commands ###
