"""empty message

Revision ID: aa67a3d40eb8
Revises: 93338be47304
Create Date: 2025-12-25 14:26:28.868400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aa67a3d40eb8'
down_revision: Union[str, None] = '93338be47304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('google_drive_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Text(), nullable=False),
    sa.Column('client_secret', sa.Text(), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=False),
    sa.Column('token_expiry', sa.DateTime(), nullable=False),
    sa.Column('folder_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('sync_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_drive_auth_id'), 'google_drive_auth', ['id'], unique=False)
    op.create_table('website_crawl_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('max_depth', sa.Integer(), nullable=False),
    sa.Column('url_patterns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('crawl_frequency', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_crawl', sa.DateTime(), nullable=True),
    sa.Column('crawl_status', sa.String(length=50), nullable=True),
    sa.Column('pages_crawled', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_crawl_config_id'), 'website_crawl_config', ['id'], unique=False)
    op.create_table('website_crawl_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('is_selected', sa.Boolean(), nullable=False),
    sa.Column('ingest_status', sa.String(length=50), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['website_crawl_config.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_website_crawl_page_id'), 'website_crawl_page', ['id'], unique=False)
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_index(op.f('ix_website_crawl_page_id'), table_name='website_crawl_page')
    op.drop_table('website_crawl_page')
    op.drop_index(op.f('ix_website_crawl_config_id'), table_name='website_crawl_config')
    op.drop_table('website_crawl_config')
    op.drop_index(op.f('ix_google_drive_auth_id'), table_name='google_drive_auth')
    op.drop_table('google_drive_auth')
    # ### end Alembic commands ###
