"""Add sync_frequency to google_drive_auth

Revision ID: ad321d227e01
Revises: 402b01ec4e0c
Create Date: 2025-12-30 03:37:55.282032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad321d227e01'
down_revision: Union[str, None] = '402b01ec4e0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_drive_auth', sa.Column('sync_frequency', sa.String(length=50), nullable=True))
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_column('google_drive_auth', 'sync_frequency')
    # ### end Alembic commands ###
