"""Add folder hierarchy to GoogleDriveFile

Revision ID: bd924bd5f7c7
Revises: efd1005423e3
Create Date: 2025-12-29 10:06:21.897448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
"""Add folder hierarchy to GoogleDriveFile

Revision ID: bd924bd5f7c7
Revises: efd1005423e3
Create Date: 2025-12-29 10:06:21.897448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd924bd5f7c7'
down_revision: Union[str, None] = 'efd1005423e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_drive_file', sa.Column('parent_folder_id', sa.String(length=512), nullable=True))
    op.add_column('google_drive_file', sa.Column('parent_folder_name', sa.String(length=1024), nullable=True))
    op.add_column('google_drive_file', sa.Column('is_folder', sa.Boolean(), nullable=False, server_default='false'))
    op.create_index(op.f('ix_google_drive_file_parent_folder_id'), 'google_drive_file', ['parent_folder_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_google_drive_file_parent_folder_id'), table_name='google_drive_file')
    op.drop_column('google_drive_file', 'is_folder')
    op.drop_column('google_drive_file', 'parent_folder_name')
    op.drop_column('google_drive_file', 'parent_folder_id')
    # ### end Alembic commands ###
