"""add_modified_at_to_google_drive_file

Revision ID: efd1005423e3
Revises: 4ab215adb170
Create Date: 2025-12-29 12:17:14.707787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd1005423e3'
down_revision: Union[str, None] = '4ab215adb170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('google_drive_file', sa.Column('modified_at', sa.DateTime(), nullable=True))
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_column('google_drive_file', 'modified_at')
    # ### end Alembic commands ###
