"""document_version

Revision ID: fe4501b3fbe3
Revises: c5a5dd5fd479
Create Date: 2025-05-02 12:51:51.228355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe4501b3fbe3'
down_revision: Union[str, None] = 'c5a5dd5fd479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('current_version_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'document', 'document_versions', ['current_version_id'], ['id'])
    # op.create_unique_constraint('unique_user_role', 'user_roles', ['user_id', 'role_id', 'company_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_constraint('unique_user_role', 'user_roles', type_='unique')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.drop_column('document', 'current_version_id')
    # ### end Alembic commands ###
